"""add download job

Revision ID: 1b4b49edaf79
Revises: 03bea7e891dd
Create Date: 2025-11-19 22:24:50.962178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b4b49edaf79'
down_revision: Union[str, None] = '03bea7e891dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloadjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'seeding', 'processing', 'completed', 'failed', name='downloadjobstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('torrent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('seed_configuration', sa.JSON(), nullable=True),
    sa.Column('seed_seconds', sa.Integer(), nullable=False),
    sa.Column('last_seed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('destination_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['bookrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloadjob')
    # ### end Alembic commands ###
